Add code coverage report generation to test.sh and upload once (#72)
* Fix test coverage reporting. For some reason, it must be a relative
path now
* Generate coverage report for test runs across Go versions
* Upload coverage report only for one Go version (it only needs to be
uploaded once)

Before:

```
ERROR: Coverage report can't be loaded, report file not found, ignoring this file src/github.com/omise/omise-go/
```

After:

```
INFO: Load coverage report from '/github/workspace/src/github.com/omise/omise-go/cover.out'
```

![Screenshot 2023-10-26 at 1 00
20 PM](https://github.com/omise/omise-go/assets/772616/9f0d970f-a499-4462-b74a-ddb06f1a9a71)